version: "3.7"
services:
  predictor-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        jwtKey: ${jwtKeyEnv}
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - .:/app
